---
title: STEM Project Grade 8
author: Tara Kenner
date: '2018-11-19'
slug: stem-project-grade-8
categories:
  - data
  - STEM
  - Chemistry
  - Chemotaxis
  - Slime Mold
tags:
  - blogdown
  - ggplot
  - highcharter
  - linear regression
  - Statistics
  - Physarum Polycephalum
---



### Title

Investigating Chemotaxis by Analyzing the Effect of Glucose/Caffeine on Physarum Polycephalum cultures.

### Introduction

I wanted to do a project that involved observations in nature and apply statistics on those observations. We take our 10-lb dog Prince on a walk everyday around the Jordan Woods Natural Area, and I’ve noticed slime molds on fallen trees…etc…This got me interested in learning more about slime molds. Per this article https://www.quantamagazine.org/slime-molds-remember-but-do-they-learn-20180709/, there are more than 900 different species of slime molds, and a particular fascinating read (also cited in “Background Information”), titled “Slime molds crack 3 of the biggest issues in the U.S” by Robby Berman, that summarizes the results of the experiments by Jonathon Keats using slime molds to crack those 3 biggest issues (Destruction of our climate, The opioid epidemic, and immigration) motivated me to further understand these problem-solving, habituated-learning and smart “neuron-less and brain-less” Physarum Polycephalum via a project.

### Questions

* How will Physarum Polycephalum respond towards varying concentrations of glucose?
     + Is there a correlation we can establish between varying concentrations of glucose and PP’s chemotaxis?
     + How will it respond when we substitute caffeine or salt for glucose?
* How long does it take a P. Polycephalum to find the glucose?
*	What are the different ways Physarum Polycephalum responds to its environment/chemical stimuli?
*	What are the various stages of growth of Physarum Plycephalum?
*	Is Physarum Polycephalum capable of optimally finding food sources and avoiding harmful stimuli?

### Variables

* Independent: Food Source:
      +	Different concentrations of glucose: 100-mM(millimolar), 10-mM, 1.0-mM, 0.1-mM, No * Glucose
      +	Different concentrations of caffeine: TBD, No Caffeine
*	Dependent: Number of PP cultures that show:
      +	Positive Growth: Towards Glucose/Caffeine
      +	Negative Growth: Away from Glucose/Caffeine
      +	Neutral Growth: Equal growth in Glucose/Caffeine or No Glucose/No Caffeine
*	Control: PP cultures, Various concentrations of Glucose/Caffeine
The experiment will be conducted using plasmodium cultures on filter paper strips soaked with the food source (as defined under Variables: Independent) in petri-dishes (5 in total with different concetrations of the food source) in our garage with minimal sunlight. The experiment will be repeated twice for the two food sources (Glucose, Caffeine). Observations(numerical and digital pictures) will be recorded. The analysis of the observations will be done using the statistical programming language R.


### Terms and Concepts (cited from Science Buddies; please see Background Information)
*	Physarum: Physarum is a genus of mycetozoan(grouping of slime molds) slime molds and Physarum Polycephalum is one of its species.
*	Eukarytotic: Organisms whose cells have a nucleus enclosed within membranes.
*	Slime mold: An informal name given to several kinds of unrelated eukaryotic orgranisms. Physarum Polycephalum is a member of slime mold.
*	Protist: Any eukaryotic organism that is not an animal, plant or fungus. The slime mold is classified as a protist.
*	Plasmodium: The vegetative phase of a two part life-cycle of a slime mold. It consists of networks of protoplasmic veins, many nuclei, and lives as a shapeless, growing blog during moist, warm weather. It’s color varies from gray, cream, colourless, to bright yellow or orange. It is during this stage that it searches for food.
*	Fruiting body: During the second phase of a slime mold, when the environment is dry, the shapeless, growing blob transforms into small stock-like fruiting bodies that are full of dust like spores.
*	Environmental cue: The information a physarum plasmodium has to rely on in search of food. It uses the information to decide whether to move towards a food source or away from the harmful substances.
*	Chemical cue: The chemical information that a plasmodium uses to decide whether to move towards or away from the chemical in question.
*	Chemotaxis: When an organism moves in repsonse to a chemical stimulus. Movement toward a higher concentration of chemical in question is termed as positive chemotaxis, while a movement in the opposite direction is negative chemotaxis.
*	Physarum polycephalum: One of the slime molds that literally translates to “many-headed slime”. It is a unicellular organism that lives in dark, cool and humid areas such as leaf litter and other organic debris.
*	Millimolar concentration: Measurement unit for the concentration of an ingredient in solution.

### Background Information:
*	Robby Berman(March 17th, 2018). Slime molds crack 3 of the biggest issues in the U.S. Retrieved October 31st, 2018, from https://bigthink.com/robby-berman/slime-molds-crack-3-of-the-biggest-issues-in-the-us. “At an event on March 2, their secretary, experimental philosopher and conceptual artist Jonathon Keats, announced the group has cracked three of America’s most vexing and controversial problems: the destruction of our climate, the opioid epidemic, and immigration. The Consortium’s secret? It brings a unique perspective to these issues. “They’re all slime molds,” says Keats. This is the first analysis of these issues by non-human scholars, he notes, asserting, “Their advice is objective, and transcends our polarized political environment because they don’t belong to our species.” (A slime mold was previously appointed to the Hampshire faculty.)"
*	Katia Moskvitch, Contributing Writer, Cognitive Science (2018, July 9). Slime Molds Remember, but do they learn? Retrieved November 15th, 2018, from https://www.quantamagazine.org/slime-molds-remember-but-do-they-learn-20180709/. “In experiments conducted by Dussutour’s team, disks of yellow slime mold (at bottom) can eat plates of oatmeal (at top) — but only if they cross gelatinous bridges (at center) laced with noxious but harmless compounds. Here, the middle slime mold sample has learned to disregard the chemicals, a process called habituation.”
*	Science Buddies Staff. (2017, July 28). Slimey Likes It! Studying Chemotaxis in Physarum Polycephalum . Retrieved October 31st, 2018, from https://www.sciencebuddies.org/science-fair-projects/project-ideas/MicroBio_p028/microbiology/chemotaxis-slime-mold. Details summary, background, materials and procedures required for the study of chemotaxis in Physarum Polycephalum with the objective of exploring chemotactic responses of P.polycephalum in culture exposed to various amounts of glucose.
*	Ferris Jabr, Nature|Scientific American (2012, November 13) How brainless slime molds redefine intelligence. Retrieved November 18th, 2018, from https://www.nature.com/news/how-brainless-slime-molds-redefine-intelligence-1.11811. “Something scientists have come to understand is that slime molds are much smarter than they look. One species in particular, the SpongeBob SquarePants–yellow Physarum polycephalum, can solve mazes, mimic the layout of man-made transportation networks and choose the healthiest food from a diverse menu—and all this without a brain or nervous system.”Slime molds are redefining what you need to have to qualify as intelligent," Reid says.”
*	Elizabeth Paine, Product Developer, retrieved November 12th, 2018, from https://www.carolina.com/teacher-resources/Interactive/think-single-celled-organisms-are-simple-think-again-the-slime-mold-physarum-polycephalum-a-single-celled-organism-for-student-investigations/tr41405.tr
*	Wkipedia: https://en.wikipedia.org/wiki/Chemotaxis

