---
title: Circle Calculation in R
author: Tara Kenner
date: '2018-02-25'
slug: circle-calculation-in-r
categories:
  - Geometry
  - Math
  - R
tags:
  - ggplot
  - highcharter
---

## Area of a circle
```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(ggforce)
```

In my math class, we are studying how to calculate the area, circumference and diameter of a circle.

```{r}
circlearea_r <- function(pi, radius) {
  
  area_circle <- pi*radius^2
}

test_circle <- circlearea_r(22/7, 5)

test_circle
```

```{r}
circlearea_d <- function(pi, diameter) {
  
  area_circle <- (pi*diameter^2)/4
}

test_circled <- circlearea_d(22/7, 12)  

test_circled
  
```

```{r}
circle_area_c <- function(pi, circum) {
  
  area_circle <- (circum^2)/(4*pi)
}
  
test_circlec <- circle_area_c(22/7, 16)
  
test_circlec


```

##Drawing circles with ggplot
```{r}
ggplot() + geom_circle(aes(x0 = 0, y0 = 0, r = 5, fill = 5))
```


```{r}
symbols (0, 0, circles=1,fg="red")
# install.packages("plotrix")
# library(plotrix)
# plot(BOD)
# draw.circle(4,14,2,border="blue",col="tan2")
```

